-- Query 3: Fetch Weekly Series Data for Anchor Merchants
-- Updated to query directly from your `staging.db` database table
-- (Translating the long-form format back to the pivoted output)

SELECT 
    w.MERCHANT_GROUP,
    SUM(CASE WHEN w.WEEK_NUM = 1 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 01 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 2 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 02 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 3 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 03 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 4 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 04 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 5 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 05 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 6 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 06 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 7 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 07 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 8 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 08 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 9 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 09 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 10 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 10 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 11 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 11 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 12 THEN w.WEEKLY_TRX ELSE 0 END) AS `TRX_Week 12 2026`,

    SUM(CASE WHEN w.WEEK_NUM = 1 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 01 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 2 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 02 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 3 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 03 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 4 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 04 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 5 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 05 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 6 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 06 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 7 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 07 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 8 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 08 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 9 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 09 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 10 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 10 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 11 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 11 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 12 THEN w.WEEKLY_VOL ELSE 0 END) AS `VOL_Week 12 2026`,

    SUM(CASE WHEN w.WEEK_NUM = 1 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 01 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 2 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 02 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 3 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 03 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 4 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 04 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 5 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 05 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 6 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 06 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 7 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 07 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 8 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 08 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 9 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 09 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 10 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 10 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 11 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 11 2026`,
    SUM(CASE WHEN w.WEEK_NUM = 12 THEN w.WEEKLY_FBI ELSE 0 END) AS `FBI_Week 12 2026`
FROM 
    WEEKLY_MONITOR w
INNER JOIN PROCESSED_MID m 
    ON w.MERCHANT_GROUP = m.MERCHANT_GROUP
WHERE 
    m.SEGMENT = 'ANCHOR'
    AND w.IS_PROCESSED_BY_ETL = 0
    AND w.EDW_FETCH_DATE >= '2026-03-01 00:00:00' 
    AND w.EDW_FETCH_DATE <= '2026-03-31 23:59:59'
GROUP BY 
    w.MERCHANT_GROUP;
